### PR TITLE
Prevent MissingAttributeException errors when Eloquent is in strict mode

### PR DESCRIPTION
**Pull request by thomasilmer**
Previous PR #321 was closed without comment. This PR has been synced with main.

### CODE REVIEW

**Comment by thomasilmer** [comment]
If anything needs to be changed, please let me know and I will update the PR.

**Comment by alexolifer** [comment]
Any answer about this bug?

**Comment by dducro** [comment]
This PR should be merged, just some small fixes, I encountered the same exception just now.

**Comment by dducro** [comment]
I forked it for now.

**Pull request closed without merging**
