### PR TITLE
Add .gitattributes to exclude some files from production environments

### PR DESCRIPTION
**Pull request by williamdes**
`git archive fixes | gzip > fixes-branch.tgz` where `fixes` is the branch name

to have a try of the effect on composer installs you can use my lib https://github.com/williamdes/mariadb-mysql-kbs

### CODE REVIEW

**Comment by Gummibeer** [comment]
Hey,
thanks for this! I've added this file already to several packages - must forgot it here.^^
In the other ones I've also excluded the `tests` dir and the `phpunit.xml` - even the `.gitignore` file.
Could I ask why these shouldn't get excluded?
Except of these additional excludes this PR looks good! :+1:

**Comment by williamdes** [comment]
Hey @Gummibeer 
When you package a repository to Debian or other providers you are happy to be able to run the tests to be sure nothing is broken

You can see here https://salsa.debian.org/phpmyadmin-team/mariadb-mysql-kbs/-/commit/444a6a8d8ad2b082420b5f62304310e09b771882#24139dae656713ba861751fb2c2ac38839349a7a that if I added the test directory I would be unable to run the tests when building the package https://salsa.debian.org/phpmyadmin-team/mariadb-mysql-kbs/-/jobs/582912#L935

**Comment by Gummibeer** [comment]
Thanks for explanation. So far I don't see any reason why this package should get added to debian packages. 🤔 
It's a PHP only package that's related to a specific Laravel project - so for me installing it via composer is the only valid way to install it!?

**Comment by williamdes** [comment]
Another example of a repo:
https://tracker.debian.org/pkg/php-nikic-fast-route
https://salsa.debian.org/php-team/pear/php-nikic-fast-route
https://github.com/nikic/FastRoute

https://tracker.debian.org/pkg/twig

> It's a PHP only package that's related to a specific Laravel project - so for me installing it via composer is the only valid way to install it!?

From an external point of view yes but in the Debian process all the dependencies must be packaged if possible

So if someone has a web app and wants it into debian he will be asked to package your package if he uses it.

I know it seems strange but it is very common, and has the benefit of if you have a security breach in this package then you will only update the packaged dependency and not have to re-package all the packages that depended on yours

**Comment by williamdes** [comment]
And also, If i think there is a bug in your package in production then I go to the vendor folder and run tests to be sure it is "okay" or not

**Comment by Gummibeer** [comment]
Okay, now I've got it. Thanks!

**Comment by williamdes** [comment]
Thank you for merging my fix, if you have any questions sometime in the future let me know

**Comment by Gummibeer** [comment]
It's merged and released - because only unused code is removed from packaged version it's a fix-release.
https://github.com/Astrotomic/laravel-translatable/releases/tag/11.7.1

**Pull request merged**
