### PR TITLE
Test suite scopes

### PR DESCRIPTION
**Pull request by Lloople**
This PR depends on #73.

It updates the tests in `ScopesTest` to use the new format.

I maintained most of the original assertions, we can change them in the future if needed 👍

#75

### CODE REVIEW

**Comment by Lloople** [comment]
Now that I see the changed files I think I did something wrong, because this PR contains also the modifications in #73 🤔

**Comment by Gummibeer** [comment]
No, everything solves itself after changing the base branch and merge the PRs one after another. 😉

**Comment by Gummibeer** [comment]
#72 is in `master` please merge it in and refactor also if needed.

**Comment by Gummibeer** [comment]
I'm sorry but I had to cherry pick your change commit and open a new PR #86 to prevent the conflicts and only merge the required changes.
The commit still uses you as author.

**Pull request closed without merging**
