### PR TITLE
add laravel 6

### LINKED ISSUE #51: Laravel 6.0 compatibility
Laravel 6.0 LTS is almost out, when can we use the package with the new version?
Thanks

### PR DESCRIPTION
**Pull request by Gummibeer**
fixes #51

### CODE REVIEW

**Comment by Lloople** [comment]
Looking forward to this 🙌

**Comment by Gummibeer** [comment]
https://twitter.com/devgummibeer/status/1168762520980656128
will try to get it done as soon as possible

**Comment by Lloople** [comment]
I had no idea! I hope you get well soon 🙏 Take your time, health goes first

**Comment by Gummibeer** [comment]
Thanks! :)
But I've also seen that https://github.com/orchestral/testbench hasn't released v4.0 until now.

**Comment by Gummibeer** [comment]
here you go: https://github.com/Astrotomic/laravel-translatable/releases/tag/v11.4.0

**Pull request merged**
