### PR TITLE
Batch of changes for package; Add Laravel 11 support

### LINKED ISSUE #384: Add PHP versions to test matrix.
PHP8.2 & 8.3 are supported but not part of the test matrix right now. They should be added to the GitHub action test matrix.

### LINKED ISSUE #385: Add Laravel11 support
Laravel 11 will be released within a few weeks - so it should be added to composer.json & GitHub action test matrix & readme/docs.

### LINKED ISSUE #388: Add PHPunit 11 support
```
There were 10 PHPUnit test runner warnings:

1) Class Country cannot be found in /home/runner/work/laravel-translatable/laravel-translatable/tests/Eloquent/Country.php

2) Class CountryStrict cannot be found in /home/runner/work/laravel-translatable/laravel-translatable/tests/Eloquent/CountryStrict.php

3) Class CountryTranslation cannot be found in /home/runner/work/laravel-translatable/laravel-translatable/tests/Eloquent/CountryTranslation.php

4) Class Person cannot be found in /home/runner/work/laravel-translatable/laravel-translatable/tests/Eloquent/Person.php

5) Class PersonTranslation cannot be found in /home/runner/work/laravel-translatable/laravel-translatable/tests/Eloquent/PersonTranslation.php

6) Class StrictTranslation cannot be found in /home/runner/work/laravel-translatable/laravel-translatable/tests/Eloquent/StrictTranslation.php

7) Class Vegetable cannot be found in /home/runner/work/laravel-translatable/laravel-translatable/tests/Eloquent/Vegetable.php

8) Class VegetableTranslation cannot be found in /home/runner/work/laravel-translatable/laravel-translatable/tests/Eloquent/VegetableTranslation.php

9) Class Astrotomic\Translatable\Tests\TestCase declared in /home/runner/work/laravel-translatable/laravel-translatable/tests/TestCase.php is abstract

10) No filter is configured, code coverage will not be processed

--

There was 1 PHPUnit test runner deprecation:

1) Your XML configuration validates against a deprecated schema. Migrate your XML configuration using "--migrate-configuration"!

WARNINGS!
```

### PR DESCRIPTION
**Pull request by Oleksandr-Moik**
Hi! First of all - sorry for such a big and dirty request)

Follows and inspired by #387 and additionally closes some issues:

- [x] Updated matrix for tests (closes #384) (inspired from [GrahamCampbell/Laravel-GitLab](https://github.com/GrahamCampbell/Laravel-GitLab/blob/7.4/.github/workflows/tests.yml) package)
- [x] Add Laravel 11 support (closes #385) (similar PRs - #387, #391)
- [x] Fixed warning and failing tests for the PHPUnit 10 (partially closes #388)
   - [x] Migrated configuration file
- [ ] Add PHPUnit 11 support - I think this can be skipped, v10 will be enough for now.
- [ ] Migrate to Laravel Pint (#381)
  - [x] Add config file `ping.json`
  - [x] Update composer script
  - [ ] Add workflow for style fix

---

Want to use this package for Laravel 11 - [see comment](https://github.com/Astrotomic/laravel-translatable/pull/395#issuecomment-2016516019)

---

I found [comment](https://github.com/Astrotomic/laravel-translatable/pull/387#issuecomment-1945760218) about "removing old versions" - is it still valid?

### CODE REVIEW

**Comment by Oleksandr-Moik** [comment]
To see how test suites works - see here https://github.com/Oleksandr-Moik/laravel-translatable/pull/1

**Comment by Oleksandr-Moik** [comment]
Any suggestions and changes are welcome)

**Comment by redalpha01** [comment]
Looking forward to having this merged.

**Comment by Oleksandr-Moik** [comment]
Hi, @Gummibeer. Can you review these changes, please?

**Comment by Oleksandr-Moik** [comment]
Hi! If you want to test or if you need to use this package for Laravel 11, I decided to add a release tag `v11.13` on my fork. 

To use it, **temporarily** add this fork to the `repositories` property of your `composer.json`:

```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/Oleksandr-Moik/laravel-translatable.git"
        }
    ],
```

and then run the following command to install the package:

```bash
composer require "astrotomic/laravel-translatable:^11.13"
```

I will keep this tag for the future but do not forget to remove it when the main package receives support for the new Laravel version. After that, I plan to remove the tag in a few weeks so that your project depends on the official source and not my fork.

So if you plan to use it - subscribe on this pull request so I can notify you via GitHub. 

Thanks for understanding!

**Pull request merged**
