### PR TITLE
Add brand new logo to the project

### PR DESCRIPTION
**Pull request by caneco**
Since [you asked](https://twitter.com/devgummibeer/status/1315038292497367040) so nicely… 😉 
Here it is your brand new logo. **Hope you like it!**

image

PS: First **Hacktoberfest** PR!!! 🥳

### CODE REVIEW

**Comment by Gummibeer** [comment]
🎉🚀💙
Damn, that was fast and great result! 🤩

I feel so bad, but one question: could/should the `A` be replaced by a `L` - for Laravel? 🤔
I've no idea about graphics and so on but in my mind this would be a great little detail!?^^

And could you add AI/SVG or any other source file? 😊

I feel so bad for not instant accepting it, so please don't think that I wouldn't be thankful! If you don't want to everything fine! 😊

**Comment by caneco** [comment]
I thought of that, but I was afraid of being too much of a cliché… 😅

image

**Comment by Gummibeer** [comment]
Looks good! 🤩
If you could push it and in best case include a source file I would be super happy! 💙

**Comment by caneco** [comment]
Done ✅

- just added the SVG option and some hi-res PNG versions;
- plus… I've added a socialcard for your repo and put it as cover in the READM.md

**Comment by Gummibeer** [comment]
Love it! 💙🎉🚀

Thanks a million times! 🤩

**Comment by Gummibeer** [comment]
https://github.com/Astrotomic/laravel-translatable/commit/dd570dfa154bf51f6e7eac16676252faaade4080
https://github.com/Astrotomic/astrotomic.info/commit/63662a6a8199aa4c2fa1ccf44651f1bd4a86e868

**Pull request merged**
