### PR TITLE
rule factory

### PR DESCRIPTION
**Pull request by Gummibeer**
**replaces:** #26

### CODE REVIEW

**Comment by FlYos** [comment]
Hey @Gummibeer,

I looked at your code, I haven't yet had the opportunity to test it, but that seems to me correct in relation to our discussion.

Maybe add a parameter in the package configuration to change the prefix and suffix globally? Same for the type of format used.

**Comment by Gummibeer** [comment]
@FlYos have some time now and will add the default delimiter configuration values.

**Comment by Gummibeer** [comment]
Will release it as `v11.3.0` - have to add a `v11.2.1` because of #40

**Comment by FlYos** [comment]
@Gummibeer perfect 👌thx a lot for this job.

**Comment by Gummibeer** [comment]
@FlYos no problem! Have to thank you for the feature request and input. :)

**Comment by FlYos** [comment]
@Gummibeer with pleasure ;-)

**Comment by Gummibeer** [comment]
https://app.gitbook.com/@astrotomic/s/laravel-translatable/package/validation-rule-factory
https://github.com/Astrotomic/laravel-translatable/releases/tag/v11.3.0

**Pull request merged**
